services:
  nodejs-image:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    image: executor-nodejs:latest

  python-image:
    build:
      context: .
      dockerfile: Dockerfile.python
    image: executor-python:latest

  java-image:
    build:
      context: .
      dockerfile: Dockerfile.jvm
    image: executor-java:latest

  nodejs-server-image:
    build:
      context: .
      dockerfile: Dockerfile
    image: executeme-nodejs-server:latest
    environment:
      - PORT=${PORT}
      - HOST_PROJECT_ROOT=${PWD}
    ports:
      - '6000:6000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./temp:/app/temp
    restart: unless-stopped
