services:
  nodejs-image:
    build:
      context: .
      dockerfile: docker/Dockerfile.nodejs
    image: executor-nodejs:latest

  deno-image:
    build:
      context: .
      dockerfile: docker/Dockerfile.deno
    image: executor-deno:latest

  python-image:
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    image: executor-python:latest

  java-image:
    build:
      context: .
      dockerfile: docker/Dockerfile.jvm
    image: executor-java:latest

  kotlin-image:
    build:
      context: .
      dockerfile: docker/Dockerfile.kotlin
    image: executor-kotlin:latest

  executeme-nginx:
    image: nginx:alpine
    ports:
      - "9292:9292"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - nodejs-server-image
    networks:
      - app-network
    restart: unless-stopped

  nodejs-server-image:
    build:
      context: .
      dockerfile: Dockerfile
    image: executeme-nodejs-server:latest
    environment:
      - PORT=${PORT}
      - HOST_PROJECT_ROOT=${PWD}
    ports:
      - "9091:9091"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./temp:/app/temp
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
