name: Create Release

on:
  push:
    branches: ["main"]
    tags:
      - v*.*.*

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release for Tag
        run: echo "TODO: we have to create a Release notes genetor CI"
        env:
          RELEASE_NOTE_WRITE: ${{ secrets.RELEASE_NOTE_WRITE }}
