name: Create Release

on:
  push:
    branches: ["main"]
    tags:
      - v*.*.*

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate Release Notes
        id: notes
        uses: RedCrafter07/release-notes-action@v1
        with:
          tag-name: ${{ github.event.inputs.tags }}
          token: ${{ secrets.GITHUB_TOKEN }}
